# This workflow will install Deno then run Deno lint and test.
# For more information see: https://github.com/denoland/setup-deno

name: Release to NPM

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@004814556e37c54a2f6e31384c9e18e983317366
        with:
          deno-version: v1.x

      - name: Set Version Output Variable
        id: vars
        run: echo ::set-output name=version::$(echo ${{github.ref_name}} | sed 's/^v//')

      - name: Set Version Environment Variable
        run: echo "NPM_VERSION=$(echo ${{github.ref_name}} | sed 's/^v//')" >> $GITHUB_ENV

      - name: Echo Version
        run: echo ${{steps.vars.outputs.version}} $NPM_VERSION
